### ISSUE TITLE
Establish a common ratio for actions in different jobs

### ISSUE THREAD

**Issue by Middie321** [SettleScape/server#40]
Specific suggestion that in filling-in missing blocks from the github jobs folder, we establish a ratio between crafter and builder. I suggest a 1 : 1.5 builder to crafter ratio, since crafting takes more time than placing, but not quite twice as long. Having a rule of thumb like this would make estimating the worth of missing blocks more efficient, and may be applied more broadly to establish thematic linkage between thematically aligned processes. For example (making up these numbers): killing a zombie = $9.5 @ 1 : 0.25 -> crafting leather = $2.38 or something to that effect. Might need more explaining, but the gist is here.

**Comment by MilesBHuff** [comment]
I think establishing ratios between the different jobs is a really good idea and will help reduce a lot of confusion regarding what blocks should be worth what.  We should absolutely do this.

However, I think Builder:Crafter::1:1.5 is strongly biased in favor of Crafter.  It's often harder to place than to craft, and this is pretty clearly evident from the large stockpiles of placeable materials every player has at their base.  Additionally, I think there are probably more crafting recipes than placeable blocks.

Accordingly, I would prefer a ratio that favors Builder over one that favors Crafter.  However, I think a sane place to start is to have the same values for both, and if it seems unbalanced after some playtesting, shift the ratio in whatever direction it needs for balance.

**Comment by slankford** [comment]
Personally, a link between builder and crafter doesn't seem to make sense since they're so functionally different. We might just need to make educated guesses based on already established crafting recipes. 

Looking at chef examples and comparing how difficult the crafting materials are to collect might also be good since we nerfed it after I tested it for a while (it was somewhat over powered at first). That's just my 2 cents of course lol.

**Comment by MilesBHuff** [comment]
That's the least-radical solution, and the least-likely to result in unbalance in the short-term;  but it also increases the amount of thought that has to go into each value.  With several thousand lines of config, we need to heuristicize wherever possible.

**Comment by MilesBHuff** [comment]
We should additionally decide on ratios between different permutations of the same block.  So, like, brick walls vs brick blocks.

**Comment by MilesBHuff** [comment]
I'm going to go ahead and close this issue, but let me know if I should reopen it.  It's pretty clear that if we go ahead with https://github.com/SettleScape/server/issues/41, we'll have to establish ratios;  and we won't know what those ratios should be until we start doing so.  Wherever possible, we'll calculate the ratios at which to start from the original blocks;  elsewhere, we'll go with a 1:1, and modify from there with playtesting.
Until then, any discussion of ratios between blocks is largely theoretical and without impact, since we'd have no way of deploying such ratios on a large scale without re-writing entire sections of the Jobs file every time we tweak a ratio.
